from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List

from ajvyra_native_tts_bridge import (
    NativeBridgeRequest,
    NativeTTSBridge,
)


@dataclass
class AudioLine:
    line_id: str
    text: str
    language: str
    character_id: str
    emotion: str = "neutral"
    pitch: float = 180.0
    speed: float = 1.0
    energy: float = 1.0


class NativeAudioPipeline:
    """
    Production layer for anime/game dialogue.

    Input:
        dialogue lines

    Output:
        real WAV files generated by AJVYRA's own
        algorithmic speech stack.
    """

    def __init__(
        self,
        output_root: str = "ajvyra_projects/audio/generated",
    ):
        self.output_root = Path(output_root)

        self.output_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.bridge = NativeTTSBridge(
            output_root=str(
                self.output_root
            )
        )

    def generate_line(
        self,
        line: AudioLine,
    ) -> Dict[str, Any]:

        filename = self._safe_name(
            line.line_id
        )

        result = self.bridge.render(
            NativeBridgeRequest(
                text=line.text,
                language=line.language,
                emotion=line.emotion,
                pitch=line.pitch,
                speed=line.speed,
                energy=line.energy,
                character_id=line.character_id,
                output_name=filename,
            )
        )

        result["line"] = asdict(line)

        return result

    def generate_batch(
        self,
        lines: List[AudioLine],
    ) -> Dict[str, Any]:

        results: List[Dict[str, Any]] = []

        for line in lines:
            try:
                results.append(
                    self.generate_line(line)
                )
            except Exception as exc:
                results.append(
                    {
                        "success": False,
                        "line_id": line.line_id,
                        "error": str(exc),
                    }
                )

        successful = [
            item
            for item in results
            if item.get("success")
        ]

        failed = [
            item
            for item in results
            if not item.get("success")
        ]

        return {
            "success": len(failed) == 0,
            "total": len(results),
            "generated": len(successful),
            "failed": len(failed),
            "results": results,
        }

    def generate_character_dialogue(
        self,
        character_id: str,
        dialogue: List[Dict[str, Any]],
        language: str = "fa",
    ) -> Dict[str, Any]:

        lines: List[AudioLine] = []

        for index, item in enumerate(dialogue, start=1):
            lines.append(
                AudioLine(
                    line_id=(
                        f"{character_id}_"
                        f"{index:04d}"
                    ),
                    text=str(
                        item.get("text", "")
                    ),
                    language=str(
                        item.get(
                            "language",
                            language,
                        )
                    ),
                    character_id=character_id,
                    emotion=str(
                        item.get(
                            "emotion",
                            "neutral",
                        )
                    ),
                    pitch=float(
                        item.get(
                            "pitch",
                            180.0,
                        )
                    ),
                    speed=float(
                        item.get(
                            "speed",
                            1.0,
                        )
                    ),
                    energy=float(
                        item.get(
                            "energy",
                            1.0,
                        )
                    ),
                )
            )

        return self.generate_batch(lines)

    def generate_multilingual_line(
        self,
        line_id: str,
        text_by_language: Dict[str, str],
        character_id: str,
        emotion: str = "neutral",
    ) -> Dict[str, Any]:

        lines = []

        for language, text in text_by_language.items():
            if language not in {"fa", "ja", "en"}:
                continue

            lines.append(
                AudioLine(
                    line_id=f"{line_id}_{language}",
                    text=text,
                    language=language,
                    character_id=character_id,
                    emotion=emotion,
                )
            )

        return self.generate_batch(lines)

    def _safe_name(self, value: str) -> str:
        allowed = (
            "abcdefghijklmnopqrstuvwxyz"
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "0123456789-_"
        )

        cleaned = "".join(
            char
            if char in allowed
            else "_"
            for char in value
        )

        return cleaned.strip("_") or "audio_line"


def demo() -> None:
    pipeline = NativeAudioPipeline()

    result = pipeline.generate_multilingual_line(
        line_id="demo_scene_001",
        text_by_language={
            "fa": "دیگه نمی‌خوام فرار کنم.",
            "ja": "もう逃げたくない。",
            "en": "I don't want to run anymore.",
        },
        character_id="original_character_01",
        emotion="cold",
    )

    print(result)


if __name__ == "__main__":
    demo()
